### ISSUE TITLE
Example of OptionT

### ISSUE THREAD

**Issue by pm-debjit-biswas** [fantasyland/fantasy-maybes#7]
Hi,

I am trying to use OptionT with the State monad from fantasy-states for handling errors in stateful computations. Are there any examples that I can refer to?

**Comment by davidchambers** [comment]
I'm about to archive this repository. @pm-debjit-biswas, if you're still interested in discussing this please open a [sanctuary-maybe][1] issue.


[1]: https://github.com/sanctuary-js/sanctuary-maybe
